java_binary(
    name = "snake_app",
        srcs = [
            "snake/app/Config.java",
            "snake/app/Direction.java",
            "snake/app/DirectionChangeHandler.java",
            "snake/app/PlayerBoard.java",
            "snake/app/PlayerGameState.java",
            "snake/app/PlayerGameState1.java",
            "snake/app/PlayerGameState2.java",
            "snake/app/Position.java",
            "snake/app/ServerErrorException.java",
            "snake/app/ServerGameState.java",
            "snake/app/SnakeApp.java",
            "snake/app/SnakePlayer.java",
            "snake/app/SnakeServer.java"
    ],
    data = glob(["images/*"]),
    main_class = "snake.app.SnakeApp"
)

java_binary(
    name = "snake_server",
    srcs = [
        "snake/app/Config.java",
        "snake/app/Direction.java",
        "snake/app/DirectionChangeHandler.java",
        "snake/app/PlayerBoard.java",
        "snake/app/PlayerGameState.java",
        "snake/app/PlayerGameState1.java",
        "snake/app/PlayerGameState2.java",
        "snake/app/Position.java",
        "snake/app/ServerErrorException.java",
        "snake/app/ServerGameState.java",
        "snake/app/SnakeApp.java",
        "snake/app/SnakePlayer.java",
        "snake/app/SnakeServer.java"
    ],
    main_class = "snake.app.SnakeServer"
)


java_binary(
    name = "snake_client",
    srcs = [
        "snake/app/Config.java",
        "snake/app/Direction.java",
        "snake/app/DirectionChangeHandler.java",
        "snake/app/PlayerBoard.java",
        "snake/app/PlayerGameState.java",
        "snake/app/PlayerGameState1.java",
        "snake/app/PlayerGameState2.java",
        "snake/app/Position.java",
        "snake/app/ServerErrorException.java",
        "snake/app/ServerGameState.java",
        "snake/app/SnakeApp.java",
        "snake/app/SnakePlayer.java",
        "snake/app/SnakeServer.java"
    ],
    data = glob(["images/*"]),
    main_class = "snake.app.SnakePlayer"
)


